source 'https://github.com/CocoaPods/Specs.git'
source 'git@192.168.1.33:Pods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target 'Walle_Example' do
  pod 'Walle', :path => '../'

end
